import type { Metadata } from "next";
import { Source_Code_Pro } from "next/font/google";

import Header from "@/components/header";
import Footer from "@/components/footer";
import { Providers } from "@/components/providers";
import { OrdersProvider } from "@/lib/orders_context";

const sourceCodePro = Source_Code_Pro({
    variable: "--font-source-code-pro",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Cars For Rent",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${sourceCodePro.variable} antialiased`}>

                {/* This runs BEFORE the page renders to set dark/light mode */}
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
      (function () {
        const theme = localStorage.getItem("theme");
        if (theme === "dark") {
          document.documentElement.classList.add("dark");
        }
      })();
    `,
                    }}
                />

                <Providers>
                    {/* <AnimatedBackground /> */}
                    <Header />
                    <main>
                        <OrdersProvider>
                            {children}
                        </OrdersProvider>
                    </main>
                    <Footer />
                </Providers>
            </body>
        </html >
    );
}
